[dev]
    command = "yarn develop"
    port = 8888
    targetPort = 8000
    publish = "public"
    autoLaunch = true
    framework = "#custom"

[[plugins]]
    package = "@netlify/plugin-functions-install-core"
